Blockly.Msg.WEBDUINO_MPU9250 = "9-axis Sensor";
Blockly.Msg.WEBDUINO_MPU9250_DETECTED = "When Detecting";
Blockly.Msg.WEBDUINO_MPU9250_DO = "Do";
Blockly.Msg.WEBDUINO_MPU9250_VAL = "value";
Blockly.Msg.WEBDUINO_MPU9250_S = "'s";
Blockly.Msg.WEBDUINO_MPU9250_STOP = "Stop Detecting";
Blockly.Msg.WEBDUINO_MPU9250_GYROSCOPE = "Gyroscope";
Blockly.Msg.WEBDUINO_MPU9250_ACCELEROMETER = "Accelerometer";
Blockly.Msg.WEBDUINO_MPU9250_MAGNETOMETER = "Magnetometer";