Blockly.Msg.WEBDUINO_LED_MATRIX = "全彩点距阵";
Blockly.Msg.WEBDUINO_LED_MATRIX_LED_SET = "设定";
Blockly.Msg.WEBDUINO_LED_MATRIX_LED_SELECT_COLOR = "选择色彩";
Blockly.Msg.WEBDUINO_LED_MATRIX_LED_BRIGHTNESS = "亮度(1~127)";
Blockly.Msg.WEBDUINO_LED_MATRIX_LED_NUMBER = "第";
Blockly.Msg.WEBDUINO_LED_MATRIX_LED_COLOR_TO = "颗色彩为";
Blockly.Msg.WEBDUINO_LED_MATRIX_CLOSE = "关闭";
